backgroundapp: "#2C3531"

#background: "#D1E8E2"
#activebackground: "#116466"
#foreground: "#116466"
#activeforeground: "#D1E8E2"

background: "#D1E8E2"
activebackground: "#116466"
foreground: "#116466"
#activeforeground: "#116466"
activeforeground: "#D1E8E2"
